### ISSUE TITLE
Inject HTML templates in each section

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/sphinx-basic-ng#7]
A useful way to make each section modular is to use a `for` loop for HTML templates in each one. 

For example, here the sphinx book theme uses a list of template paths to insert content into the sidebar:

https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/sidebar.html#L13

This one follows the sphinx pattern:

```python
html_sidebars = {
  "**": ["path/to/template.html"],
  "page-specific-sidebar": ["path/to/template.html"],
}
```

but we could imagine having a similar config for other parts of the page and doing this at the theme level e.g.:

```python
html_theme_options = {
    "announcement": ["components/demos/announcement-demo.html"],
    "header": ["components/demos/header-demo.html"],
    "sidebar_left": ["components/demos/sidebar-left-demo.html"],
    "sidebar_right": ["components/demos/sidebar-right-demo.html"],
    "middle_content": ["components/demos/middle-content-demo.html", "components/page-content.html", ],
    "footer": ["components/next-prev.html"],
}
```

Then to extend a section of the base theme, one would define sidebar templates and then just add them to the proper list in the configuration. Obviously if they needed to make _major_ changes to a section, they might want to directly edit that template themselves, but I think this could be a lightweight way to extend sections without having to modify the base HTML.

Then this theme and any sub-themes would be a combination of two things:

- **sections** are high-level groups of components in specific locations (e.g., `sidebar-left`, `content-main`, `content-footer`
- **components** are templates that can be inserted into any section's component list via configuration variable.

WDYT?

**Comment by choldgraf** [comment]
I will try and put together a lightweight PR to describe what I mean

**Comment by mgeier** [comment]
If you want this to work with your `theme.conf` (without needing Python code in a Sphinx extension), you can use this little trick I've come up with:

https://github.com/mgeier/insipid-sphinx-theme/blob/d945ea543137acec0d99bd34e581cfd65f0a5ab2/src/insipid_sphinx_theme/insipid/layout.html#L4-L10

If you know a better way, please let me know!

**Comment by choldgraf** [comment]
Ah very clever! I have added that here #8

**Comment by pradyunsg** [comment]
Is this a suggestion for how to handle #2?

As I noted there, I really really really don't want to be using theme_options for this, because Sphinx allows end-users to customise those fairly easily and I don't want that knob accessible easily.

Why is this preferable to having blocks in the template that are overridden? It seems functionally equivalent to me, and if a downstream theme wants to provide those knobs it can. (I don't want Furo to, but it makes a lot of sense for SBT and pydata-sphinx-theme)

**Comment by choldgraf** [comment]
> Why is this preferable to having blocks in the template that are overridden?

I am thinking of the perspective of a theme author. I want to have to write as little HTML templating as possible. The benefit of just providing lists of `elements` in your config is that you don't have to touch *any* HTML at the page level, you just provide a list of element paths. If you want to define a custom element and add it then you can just write a small HTML snippet in your theme's templates folder, and then refer to it in the theme's configuration. To me that's simpler than having to over-load a template file each time. But again, I am just exploring design space right now, not trying to make decisions.

> because Sphinx allows end-users to customise those fairly easily and I don't want that knob accessible easily to end users

To me the question of whether it is in `html_theme_options` is an implementation detail - it could be in some other configuration as well it just seemed natural there to me. I'd think a theme author can always just not document what they don't want users to use. I don't think most users would ever realize that an option like this was available unless the theme author decided to document it. And IMO if something isn't documented, then users likely won't discover it + can assume no promises made about supporting it.

**Comment by pradyunsg** [comment]
(AAAAAAAAAAAAAAAAAAAA, I'm doing walls of text)

> And IMO if something isn't documented, then users likely won't discover it + can assume no promises made about supporting it.

Yes, but this breaks down when the number of users increase. 🙈

https://www.hyrumslaw.com/

And, in an ideal world, that'd be true for more than one of the themes that derive from this.

> I am thinking of the perspective of a theme author. I want to have to write as little HTML templating as possible.

I'm thinking of this as a theme author who doesn't want to give his end users any powerful knobs, documented or undocumented. 🙃 

I guess my expectation is that in the simplest case, theme authors would be writing a few files that basically are blocks-containing-a-bunch-of-includes / {{ toc }} and the CSS for these and no HTML basically.

I also feel like expecting a theme author to interact with the templates is OK (they have to write some anyway). To me, the point of this whole effort is to minimise the amount of that template writing that'd get duplicated across projects.

> If you want to define a custom element and add it then you can just write a small HTML snippet in your theme's templates folder, and then refer to it in the theme's configuration. To me that's simpler than having to over-load a template file each time.

Hmm... To me, this kind of thing seems pretty straightforward with Jinja2 blocks as well:

I guess this is the sort of thing you'd do in something like `elements/primary-sidebar.html` with:

```jinja2
{% include "my-fancy-thing.html" %}
```

If you wanna do this in page.html for some reason, that's doable too!

```jinja2
{% block primary_sidebar %}
{{ super() }}
{% include "my-fancy-additional-thing.html" %}
{% endblock %}
```

> But again, I am just exploring design space right now, not trying to make decisions.

Yup yup. I didn't mean to imply otherwise. I just feel strongly that we shouldn't use theme_options for exposing things to theme authors. Part of the reason behind that is that I've dealt with a lot of backwards compatibility pain, arising from users depending on undocumented things (or things clearly marked "don't use this"), and then getting strong pushback when those things change. :)

Even if it'll end up being a case of telling those users that it's not supported by the theme; it's still additional cost to be paid. And I think its a bit more than that as well, but that's the major one. (lack of consistency across documentation sites using said theme, potential for misuse due to create poorly designed structures etc come to mind)

**Comment by choldgraf** [comment]
yeah that is reasonable to me 👍 I understand your perspective about not complexifying the basic skeleton theme too much. Perhaps this is something that can be done at the sub-theme level
